### ISSUE TITLE
resize H1 Titles on mobile

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#306]
**Describe the bug**
h1 titles cause reasonable length names to wrap

**To Reproduce**
Go to [Stephen Duncombes page](https://c4aa.org/about/stephen-duncombe)
Set to mobile width

**Expected behavior**
Font would scale

**Screenshots**

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/da00adfd-d389-4fb4-9546-c6d8a2a81a41)

**Desktop (please complete the following information):**
 - iOS
 - Safari

**Smartphone (please complete the following information):**
 - iPhone something something

**Additional context**

It could switch to a size relative to `vw` on mobile?

This is around line 100 on `_03_generic.scss`

```css
header.featured-image h1.entry-title {
	margin-left: .5em;
	margin-right: .5em;
	font-size: 2rem; // fallback
	// @see https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/
	font-size: clamp(1.5rem, calc( -0.2647rem + 7.8431vw ), 3.5rem);
}
```
